name: StepFunction Deployment Monitoring
author: FreeAgent
description: Polls a step function until completion.
outputs:
  deployment_failed:
    description: true or false depending on whether the deployment failed
  deployment_failure_reason:
    description: A brief explanation on why the deployment failed

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.EXECUTION_ARN }}
